language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install psycopg2
script:
  - pytest --cov=app

services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database test_politico;' -U postgres
  - export FLASK_ENV=testing
  - psql -c 'CREATE DATABASE politico' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres


after_success:
  - coveralls


    
env:
  - SECRET_KEY="wqeretyuiyodfhj21" DB_NAME="politico" DB_USER="fram" DB_HOST="localhost" DB_PASSWORD="123" DB_TEST_NAME="test_politico"
