language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=app

services:
  - postgresql
addons:
  postgresql: "9.5"

before_script:
  - psql -c 'create database test-politico;' -U postgres
  - psql -c 'CREATE DATABASE politico' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres


after_success:
  - coveralls

  services:
    - postgresql
    
env:
export SECRET_KEY="wqeretyuiyodfhj21" DATABASE_URL='postgres://cjruocpbcmuivf:714adec5a08ddc9b1401b71c9736b680b2f889df999961e9b2a32d03ad4e26fd@ec2-50-17-193-83.compute-1.amazonaws.com:5432/dc0796g0mvp2ns  
